---
title: "First Knit"
author: "Shawn Olson"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended William J Pete Knight and graduated. I feel like english class was easier than math. The subject I did the best in was English 12.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  The computer that i have at home is a windows computer. On a scale from 1 to 10 i would say my computer knowledge is a 7. I would say that the internet where i live is pretty good.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My perferred name to be called by is my first name which is Shawn.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  What i want to achieve in life is getting a good job and making alot of money for me and my family by doing something im passionate about. I believe the college subject that would be my greatest interest would be the one that im taking right now which is Computer Applications.  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
  I have not gone to any foreign countries yet. One were i would go to in the future would be Europe. I have not been in the miltary but if i were drated i would want to work in the communicatins field becuase i feel like i would be good at it.   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
 I havent taken any math courses prior to the one that im in right now which is math 116. I believe that i need atleast a C in this class in order to not upset my future plans.
 






  




